#!/bin/bash

#SBATCH -J miniaste
#SBATCH -o miniaste.%j.out
#SBATCH -e miniaste.%j.err
#================================================
# Tile size 30x30
##SBATCH -N 94
##SBATCH -n 3957
#================================================
# Tile size 40x40
##SBATCH -N 53
##SBATCH -n 2238
#================================================
# Tile size 45x45
##SBATCH -N 42
##SBATCH -n 1779
#================================================
# MINI ASTE 
#SBATCH -N 1
#SBATCH -n 36
#================================================
#SBATCH -t 6:00:00
#SBATCH -p skx-normal
#SBATCH -A Polar-Project
#SBATCH --reservation=ECCO19School

#SBATCH --mail-user=ivana@oden.utexas.edu
#SBATCH --mail-type=begin
#SBATCH --mail-type=end

## Set up suffix for run
#   adjoint run: "_ad"
#   forward run: "" 
suff=""

## Set up code version: blank if current version
vers="_c67c"

## Set up file extensions: blank if no extension
ext=""

## Specify parallel domain decomposition:
#   Read SIZE.h or data.exch2 for sNx, sNy, and nPx
sNx="30"
sNy=$sNx
nPx="36"

## Set up pickup time step file extension: '00000000' if no pickup
#pkup="0000000000"
#pkup="0000000001"
#pkup_prev="0000010XXXX"

## =============================================================================
## Set up directories:
scratchDir=$SCRATCH/llc/llc90/aste_90x150x60
exeDir=$scratchDir/run$vers${ext}_pk
## =============================================================================
### Run in the $SCRATCH project directory ###
cd $exeDir

module restore
module load remora
set -x
date>run.MITGCM.timing
remora ibrun -n $nPx mitgcmuv
date>>run.MITGCM.timing
