#!/bin/bash

#SBATCH -J notide4320
#SBATCH -o notide.%j.out
#SBATCH -e notide.%j.err
#================================================
# Tile size 30x30
#SBATCH -N 84
#SBATCH -n 3957
#================================================
#SBATCH -t 42:19:00
#SBATCH -p skx-normal
#SBATCH -A Transfer-of-ECCO-glo
#SBATCH --mail-user=ivana@oden.utexas.edu
#SBATCH --mail-type=all

## Set up suffix for run
#   adjoint run: "_ad"
#   forward run: "" 
suff=""

## Set up code version: blank if current version
vers="_c67h"

## Set up file extensions: blank if no extension
ext="_no_tidal_bc"

## Specify parallel domain decomposition:
#   Read SIZE.h or data.exch2 for sNx, sNy, and nPx
sNx="30"
sNy=$sNx
nPx="3957"

## Set up pickup time step file extension: '0000000000' if no pickup
### Picking up from the 5 week "warm up" run on sverdrup
pkup="0000000001"
pkup_prev="0000268800"

## =============================================================================
## Set up directories:
scratchDir=$SCRATCH/llc/llc4320/NA_4320x2160x1080x90
exeDir=$scratchDir/run$vers${ext}_pk$pkup
## =============================================================================
### Run in the $SCRATCH project directory ###
cd $exeDir

module restore
module load remora
set -x
date>run.MITGCM.timing
#ibrun tacc_affinity mitgcmuv
remora ibrun -n $nPx mitgcmuv
date>>run.MITGCM.timing
