#!/bin/bash
#SBATCH -J tidePkg
#SBATCH -o bash.out/NA4320.%j.out
#SBATCH -e bash.out/NA4320.%j.err
## A time limit of 0 means no time limit is to be set
#SBATCH -t 0
#SBATCH -N 11
#SBATCH -n 257
#SBATCH --mail-user=ivana@utexas.edu
#SBATCH --mail-type=all

date > run.MITGCM.timing
mpiexec --mca btl ^tcp,openib --mca mtl psm2 mitgcmuv 
date >> run.MITGCM.timing
