#!/bin/bash
## Copy this into your problem directory and modify to your needs

## Set up suff for run: 
#	"_ad": adjoint
#	"":    forward
suff=""

## Set up code version: blank if current version
vers="_c67c"

## Set up directories:
#	root_dir: MITgcm code
#	exp_dir:  Problem run
#		  Ex: ~ivana/llc/llc4320/NA_4320x2160x1080x90/root/
root_dir=$HOME/MITgcm$vers
exp_dir=$PWD #symlink to ~ivana/MITgcm_c67c/mysetups/NA_4320x2160x1080x90/root/
build_dir=$exp_dir/build$vers$suff
code_dir=$exp_dir/code$vers$suff
inp_dir=$exp_dir/namelists$vers$suff

## Opt file architecture specific
stampede_opt=$env_setups/optfiles/linux_amd64_ifort+mpi_stampede
lonestar_opt=$env_setups/optfiles/linux_amd64_ifort+mpi_lonestar
lonestar_profile_opt=$env_setups/optfiles/linux_amd64_ifort+mpi_lonestar+profile
sverdrup_opt=$env_setups/optfiles/linux_amd64_ifort+mpi_sverdrup

## Use the correct opt file here
build_cmd="$root_dir/tools/genmake2 -rd=$root_dir -mods=$code_dir
-optfile=$sverdrup_opt -mpi"

## Check which run to set up
if [[ $suff == "_ad" ]]
  then
        echo "Preparing adjoint run ..."
elif [[ $suff == "" ]]
  then
        echo "Preparing forward run ..."
else
        echo "Unsure of suffix, exiting ..."
        exit 1
fi

## Build the model in build directory
if [ ! -d $build_dir ]
  then
        mkdir $build_dir
        cd $build_dir
else
        cd $build_dir
        if [ -s Makefile ] ; then
		make clean
	fi
fi

cd $build_dir
echo "Inside dir: "$PWD

echo "Evaluating: "$build_cmd
eval $build_cmd 
echo "Make depend ..."
eval "make depend" 
echo "Making executable ..."
if [[ $suff == "_ad" ]] ; then
  eval "make -j 4 adall" 
else
  eval "make -j 4"
fi
