#!/bin/bash

## Set up fwdAdj for run: 
#	"_ad": adjoint
#	"":    forward
fwdAdj=""

## Set up code version: blank if current version
vers="_c67h"

## Set up file extensions: blank if no extension
ext="_no_tidal_bc"

## Specify parallel domain decomposition:
#   Read SIZE.h or data.exch2 for sNx, sNy, and nPx
sNx="36"
sNy=$sNx
nPx="2752"

## Set up pickup time step file extension: '0000000000' if no pickup
### Picking up from the 5 week "warm up" run on sverdrup
pkup="0000307200"
pkup_prev="0000076800"

## =============================================================================
## Set up directories:
#   gcmDir:   MITgcm code
#   srcDir:    Problem run
#       Ex: in sverdrup: ~ivana/llc/llc4320/NA_4320x2160x1080x90/root
gcmDir=$HOME/MITgcm$vers
srcDir=$PWD # $WORK/llc/llc4320/NA_4320x2160x1080x90/no_tidal_bc
buildDir=$srcDir/build$vers$fwdAdj
codeDir=$srcDir/code$vers$fwdAdj
inpDir=$srcDir/namelists$vers$fwdAdj

scratchDir=$SCRATCH/llc/llc4320/NA_4320x2160x1080x90
exeDir=$scratchDir/run$vers${ext}_pk$pkup

submit_script=$srcDir/submit_scratch_pk${pkup}$fwdAdj
## =============================================================================
## Create executing directory: where gcm output will go
if [ ! -d $exeDir ] ; then
	echo "Making "$exeDir" ..."
    mkdir $exeDir
else
    echo "Moving to "$exeDir" ..."
fi        
cd $exeDir

if [ ! -d "diags" ] ; then
    mkdir diags
fi
## =============================================================================
## Link problem information
echo "Grabbing necessary files ..."

# Submission and linking scripts
cp $submit_script .
cp $srcDir/link_run_pk${pkup} .

# SIZE.h
cp -f $codeDir/SIZE.h .

# Executable
cp -f $buildDir/mitgcmuv_${sNx}x${sNy}x${nPx}$fwdAdj mitgcmuv

# Namelists
cp -f $inpDir/* .
if [ ! -f "$inpDir/data.exch2_${sNx}x${sNy}x$nPx" ]; then
    echo "Check for correct data.exch2 file"
    exit 1
else
    cp -f $inpDir/data.exch2_${sNx}x${sNy}x$nPx data.exch2
fi

# 6 hour forcing files
forcingDir=$STOCKYARD/stampede2/forcing
if [ ! -d /.jra55 ]; then
    ln -sf $forcingDir/jra55 .
    ln -sf $forcingDir/jra55xx .
fi

# binary files
dataDir=$srcDir/run_template
ln -sf $dataDir/input_binaries/* .
ln -sf $dataDir/input_obcs/*.bin .

## =============================================================================
## Setup pickups: 
#   WARNING: copy instead of link to avoid overwriting output
if [[ $pkup_prev ]]; then
    echo "Linking pickup data..."
    pkupDir=$scratchDir/no_tidal_bc/run${vers}${ext}_pk$pkup_prev
    if [[ ! -f pickup.${pkup}.meta ]]; then     
        cp -f $pkupDir/pickup.${pkup}.data .
        cp -f $pkupDir/pickup.${pkup}.meta .
    else
        echo "Already copied pickup files..."
    fi
fi

echo "Ready to execute ..."

## =============================================================================
## list of linked files
ls -l *.bin > linked_list
ls -l tile* >> linked_list

## =============================================================================
echo ""
echo "*** Pro tips: "
echo "      - Check data.pkg: useOBCS = .true.? usePROFILES = .false.? "
echo ""
echo "      - Check data: "
echo "           nTimeSteps correct? tapes directory uncommented? adjDump = false?"
echo ""
echo "      - Check data.diagnostics: have the filenames set with diags/ prefix? "
echo ""
echo "      - Check data.exf: directory set for correct forcing files? period correct?"
echo ""
echo "      - Check submit file for .."
echo "           Correct queue? "
echo "           forward run: <exec> mitgcmuv "
echo "           adjoint: <exec> mitgcmuv_ad "
echo "           walltime correct? " 
echo ""
echo "Assuming this is done, ready for launch ... "
echo ""
echo ""
