#!/bin/bash

#SBATCH -J miniaste
#SBATCH -o miniaste.%j.out
#SBATCH -e miniaste.%j.err
#================================================
### MINI ASTE 
#SBATCH -N 1
#SBATCH -n 36
#================================================
#SBATCH -t 0:30:00
#SBATCH -p skx-dev
#SBATCH -A Polar-Project
#SBATCH --mail-user=ivana@oden.utexas.edu
#SBATCH --mail-type=all
## =============================================================================
## Set up suffix for run
#   adjoint run: "_ad"
#   forward run: "" 
suff=""

## Set up code version: blank if current version
vers="_c67d"

## Set up file extensions: blank if no extension
ext=""

## Specify parallel domain decomposition:
#   Read SIZE.h or data.exch2 for sNx, sNy, and nPx
sNx="30"
sNy=$sNx
nPx="36"

## Set up pickup time step file extension: '00000000' if no pickup
pkup="0000000000"
#pkup="0000000001"
#pkup_prev="0000010XXXX"

## =============================================================================
## Set up directories:
scratchDir=$SCRATCH/llc/llc90/aste_90x150x60
exeDir=$scratchDir/run$vers${ext}_pk$pkup
## =============================================================================
### Run in the $SCRATCH project directory ###
cd $exeDir

module restore
module load remora
set -x
date>run.MITGCM.timing
remora ibrun -n $nPx mitgcmuv
date>>run.MITGCM.timing
