#!/bin/bash

#SBATCH -J tide4320
#SBATCH -o tide.%j.out
#SBATCH -e tide.%j.err
#================================================
# Tile size 36x36
#SBATCH -N 116
#SBATCH -n 2752
#================================================
#SBATCH -t 23:59:00
#SBATCH -p normal
#SBATCH -A Transfer-of-ECCO-glo
#SBATCH --mail-user=ivana@oden.utexas.edu
#SBATCH --mail-type=all

## Set up suffix for run
#   adjoint run: "_ad"
#   forward run: "" 
suff=""

## Set up code version: blank if current version
vers="_c67h"

## Set up file extensions: blank if no extension
ext="_tidal_bc"

## Specify parallel domain decomposition:
#   Read SIZE.h or data.exch2 for sNx, sNy, and nPx
sNx="36"
sNy=$sNx
nPx="2752"

## Set up pickup time step file extension: '0000000000' if no pickup
### Picking up from the 5 week "warm up" run on sverdrup
pkup_prev="0000000001"
pkup="0000249600"

## =============================================================================
## Set up directories:
scratchDir=$SCRATCH/llc/llc4320/NA_4320x2160x1080x90
exeDir=$scratchDir/run$vers${ext}_pk$pkup
## =============================================================================
### Run in the $SCRATCH project directory ###
cd $exeDir

module restore
#module load remora
set -x
date>run.MITGCM.timing
ibrun tacc_affinity mitgcmuv
#remora ibrun -n $nPx mitgcmuv
date>>run.MITGCM.timing
