#!/bin/bash
#SBATCH -J v4r4
#SBATCH -o run.%j.out
#SBATCH -e run.%j.err
## A time limit of 0 means no time limit is to be set
#SBATCH -t 0
#SBATCH -N 4
#SBATCH -n 96
#SBATCH --mail-user=ivana@utexas.edu
#SBATCH --mail-type=all

date > run.MITGCM.timing
mpiexec --mca btl ^tcp,openib --mca mtl psm2 mitgcmuv 
date >> run.MITGCM.timing
